query Me {
  me {
    id
    email
    displayName
    gender
    avatarUrl
    bio
    phone
    dob
    locationName
    locationLat
    locationLong
    timezone
    locale
    emailVerified
    isActive
    createdAt
    updatedAt
  }
}
