query RecoveryAssessmentHistory {
  recoveryAssessmentHistory {
    id
    userId
    journeyId
    dailySessionId
    overallScore
    emotionalDistress
    acceptance
    selfAwareness
    selfWorth
    emotionalStability
    readinessToMoveForward
    createdAt
    updatedAt
  }
}
