export const LandingRoutes = {
  Landing: 'Landing',
  WhatBringsYouHere: 'WhatBringsYouHere',
  HowLongHasItBeen: 'HowLongHasItBeen',
  HowAreYouFeeling: 'HowAreYouFeeling',
  WhatWouldYouLikeHelpWith: 'WhatWouldYouLikeHelpWith',
  MeetYourAI: 'MeetYourAI',
  CreateAccount: 'CreateAccount',
  Reminder: 'Reminder',
  RecoveryStartsToday: 'RecoveryStartsToday',
  Login: 'Login',
  CreatePassword: 'CreatePassword',
  VerifyEmail: 'VerifyEmail',
  ForgotPassword: 'ForgotPassword',
  VerifyIdentity: 'VerifyIdentity',
} as const;
